package com.itsikh.buddy.data.models

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey
import java.util.UUID

/**
 * A record of one conversation session with Buddy.
 *
 * Written at session start with minimal data, then updated when the session ends.
 * After the session, [MemoryExtractor] fills in [sessionSummary] (a Claude-generated
 * Hebrew summary for the parent dashboard).
 *
 * Session logs are also written to Google Drive AppData as structured JSON so a future
 * parent companion app can consume them.
 */
@Entity(
    tableName = "session_logs",
    foreignKeys = [ForeignKey(
        entity = ChildProfile::class,
        parentColumns = ["id"],
        childColumns = ["profileId"],
        onDelete = ForeignKey.CASCADE
    )],
    indices = [Index("profileId")]
)
data class SessionLog(
    @PrimaryKey val id: String = UUID.randomUUID().toString(),
    val profileId: String,
    val mode: ChatMode,
    val startedAt: Long = System.currentTimeMillis(),
    val endedAt: Long? = null,
    val durationMinutes: Int = 0,
    val turnCount: Int = 0,
    val newWordsIntroduced: Int = 0,
    val buddyCorrections: Int = 0,

    /** Hebrew summary generated by Claude after the session ends. Shown in parent dashboard. */
    val sessionSummary: String? = null,

    val xpEarned: Int = 0
)

enum class ChatMode {
    FREE_CHAT,
    STORY_TIME,
    ROLE_PLAY
}
